Documentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/AbcSize:
  Exclude:
    - models/final_frame.rb

Style/FrozenStringLiteralComment:
  Enabled: false