version: 2
jobs:
  build:
    docker:
      - image: ruby:2.6.1

    working_directory: /home/jobsity-game
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rubocop
      - run: bundle exec rspec
