version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node

    working_directory: /home/jobsity-game
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rubocop
      - run: bundle exec rspec