version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2 # Ruby orb registry: https://circleci.com/orbs/registry/orb/circleci/ruby

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.1-stretch-node
    steps:
      - checkout
      - run: gem install bundler:2.0.2
      - run: bundle install
      - run: bundle exec rubocop
      - run: bundle exec rspec